version: "3"

services:
  mysql:
    container_name: todo_mysql
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./repository/mysql/init/:/docker-entrypoint-initdb.d
      - ./repository/mysql/init/my.cnf:/etc/mysql/my.cnf
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  postgres:
    container_name: todo_postgres
    image: postgres:13
    platform: linux/amd64
    ports:
      - 5432:5432
    volumes:
      - ./repository/postgres/init/:/docker-entrypoint-initdb.d
      - ./repository/postgres/init/postgresql.cnf:/etc/postgresql/postgresql.conf
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}

  back:
    container_name: todo_back
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  db-data:
    driver: local
