openapi: 3.0.2
info:
  title: Go Clean Architecture API
  description: <b>Go Clean Architecture API Documentation</b><br>
  version: 1.0.0
servers:
  - url: http://localhost:8083/
tags:
  - name: task
    description: Task-related APIs
paths:
  /api/task/get:
    get:
      tags:
        - task
      summary: Task Retrieval API
      description: |
        Retrieves task information based on the ID provided in the URL query.
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: Task ID
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTaskResponse'
  /api/task/list:
    get:
      tags:
        - task
      summary: Task List Retrieval API
      description: |
        Retrieves a list of task information.
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTasksResponse'
  /api/task/create:
    post:
      tags:
        - task
      summary: Task Creation API
      description: |
        Creates task information.
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
        required: true
      responses:
        200:
          description: A successful response.
  /api/task/update:
    put:
      tags:
        - task
      summary: Task Update API
      description: |
        Updates task information.
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
        required: true
      responses:
        200:
          description: A successful response.
  /api/task/delete:
    delete:
      tags:
        - task
      summary: Task Deletion API
      description: |
        Deletes task information based on the ID provided in the URL query.
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: Task ID
      responses:
        200:
          description: A successful response.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    GetTaskResponse:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        title:
          type: string
          example: "Task Title"
        description:
          type: string
          example: "Task Description"
        due_date:
          type: string
          example: "2021-01-01T00:00:00Z"
        priority:
          type: integer
          example: 1
        created_at:
          type: string
          example: "2021-01-01T00:00:00Z"
    ListTasksResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/GetTaskResponse'
    CreateTaskRequest:
      type: object
      properties:
        title:
          type: string
          description: Task title
          example: "Task Title"
        description:
          type: string
          description: Task description
          example: "Task Description"
        due_date:
          type: string
          description: Task due date
          example: "2021-01-01T00:00:00Z"
        priority:
          type: integer
          description: Task priority
          example: 1
    UpdateTaskRequest:
      type: object
      properties:
        id:
          type: string
          description: Task ID
          example: "12345"
        title:
          type: string
          description: Task title
          example: "Task Title"
        description:
          type: string
          description: Task description
          example: "Task Description"
        due_date:
          type: string
          description: Task due date
          example: "2021-01-01T00:00:00Z"
        priority:
          type: integer
          description: Task priority
          example: 1